import { GREEN_SCREEN_INSTRUCTION_EN, GREEN_SCREEN_INSTRUCTION_ZH } from "./chromaKeyPrompt";

export const DEFAULT_STANDARD_PROMPT_EN = `Create a clean 5×3 PNG sprite sheet for Windows cursor production. Each of the 15 cells must be exactly equal and designed for final 128×128 output. Keep every character fully inside a visible 12% safe margin on all four sides; no hair, hand, prop, glow, shadow, cursor symbol, or outline may touch or cross a cell boundary. Use one consistent chibi hero with a compact silhouette, but change the pose and expression for each cursor function. Place the exact Windows work-item symbol in the upper-left safe corner, separated from the character. Use a solid white interior/fill with crisp black outline/linework for every symbol; no colored fill, gray halo, or black-filled arrow. ${GREEN_SCREEN_INSTRUCTION_EN} No horizontal lines, speed lines, cell dividers, checkerboard, watermark, cropped body parts, or overlapping neighboring cells. Row order: 1–5 standard select, text select, busy, background busy, precision select; 6–10 handwriting, unavailable, vertical resize, horizontal resize, diagonal resize; 11–15 move, alternate select, handwriting candidate, link select, location select.`;

export const DEFAULT_STANDARD_PROMPT_ZH = `建立一個乾淨的 5×3 PNG 精靈圖，用於製作 Windows 遊標。15 個單元格必須完全相等，並設計為最終 128×128 輸出格式。每個角色都必須完全位於四邊 12% 的可見安全邊距內；頭髮、手、道具、發光、陰影、遊標符號或輪廓都不得觸及或跨越單元格邊界。使用一個輪廓緊湊的 Q 版角色，但根據每個遊標功能更改姿勢和表情。將精確的 Windows 工作項目符號放置在左上角的安全區域，並與角色分開。每個符號都使用純白色填充，並帶有清晰的黑色輪廓線；不得使用彩色填充、灰色光暈或黑色填充的箭頭。生成請使用純綠色（#00FF00）作為暫時去背背景，讓角色邊緣能被精準辨識。不得有水平線、速度線、單元格分隔線、棋盤格、浮水印、裁剪的身體部位或重疊的相鄰單元格。行順序：1–5 行為標準選擇、文字選擇、忙碌、背景忙碌、精確選擇；6–10 行為手寫、不可用、垂直調整大小、水平調整大小、對角線調整大小；11–15 行為移動、交替選擇、手寫候選、連結選擇、位置選擇。`;

export function buildStandardPrompt(characterDirection: string) {
  return `${DEFAULT_STANDARD_PROMPT_EN}\n\n中文規格：\n${DEFAULT_STANDARD_PROMPT_ZH}\n\nCharacter direction: ${characterDirection}.`;
}
