const width = 32;
const height = 32;
const dibSize = 40;
const rowBytes = Math.ceil(width / 32) * 4;
const imageSize = width * height * 4 + rowBytes * height;
const buffer = new ArrayBuffer(6 + 16 + dibSize + imageSize);
const view = new DataView(buffer);
let offset = 0;
const u16 = (v) => { view.setUint16(offset, v, true); offset += 2; };
const u32 = (v) => { view.setUint32(offset, v, true); offset += 4; };
const i32 = (v) => { view.setInt32(offset, v, true); offset += 4; };
u16(0); u16(2); u16(1); view.setUint8(offset++, width); view.setUint8(offset++, height); view.setUint8(offset++, 0); view.setUint8(offset++, 0); u16(0); u16(0); u32(dibSize + imageSize); u32(22);
u32(dibSize); i32(width); i32(height * 2); u16(1); u16(32); u32(0); u32(width * height * 4); i32(0); i32(0); u32(0); u32(0);
offset += width * height * 4;
const mask = new Uint8Array(buffer, offset, rowBytes * height); mask.fill(0);
if (view.getUint16(0, true) !== 0 || view.getUint16(2, true) !== 2) throw new Error('bad CUR header');
const bytesInRes = view.getUint32(14, true);
const imageOffset = view.getUint32(18, true);
if (bytesInRes !== dibSize + imageSize) throw new Error(`bad bytesInRes ${bytesInRes}`);
if (imageOffset !== 22) throw new Error(`bad imageOffset ${imageOffset}`);
if (view.getInt32(imageOffset + 8, true) !== height * 2) throw new Error('bad doubled DIB height');
if (buffer.byteLength !== imageOffset + bytesInRes) throw new Error('payload length mismatch');
console.log(JSON.stringify({ ok: true, fileBytes: buffer.byteLength, bytesInRes, imageOffset, maskBytes: mask.byteLength }));
